#! /bin/sh

find . -name '*.c' -o -name '*.h' | \
	xargs grep MXSLT_DBG | \
	sed -e 's/.*\(MXSLT_DBG[_A-Z0-9]*\).*/\1/' | \
	sort | uniq -c

#find . -name '*.c' -o -name '*.h' | \
#	xargs grep MXSLT_DBG | \
#	sed -e 's/[[:space:]]/\n/g' -e 's/[(),]//g' | \
#	grep MXSLT_DBG | sort | uniq -c
