#!/bin/bash

server=${server-togliatti}

[ ! -f "configure.ac" ] && {
  echo 1>&2 "Must be run from mod-xslt root!"
  exit 1
}

[ ! -d "../http" ] && {
  echo 1>&2 "../http does not exist!"
  exit 1
}

rsync -avz -e ssh --exclude archive/ --exclude people/ --delete ../http/http/ \
	scp@$server:/home/http/mod-xslt2.com/http

rsync -avz -e ssh --exclude archive/ --exclude people/ --delete ../http/lib/ \
	scp@$server:/home/http/mod-xslt2.com/lib

rsync -avz -e ssh ../http/http/software/ scp@$server:/home/http/mod-xslt2.com/http/software/
